In [2]:
import pandas as pd
import numpy as np
import random

In [3]:
linhas = []
for i in range(1, 254):
    id_treinador_batalha = i
    id_treinador = random.randint(1, 253)
    id_batalha = random.randint(1, 253)
    linhas.append([id_treinador_batalha, id_treinador, id_batalha])

df_pokemon = pd.DataFrame(linhas, columns=['id_treinador_batalha', 'fk_treinador_id', 'fk_batalha_id'])
df_pokemon.to_csv('../output_data/popular_treinador_batalha.csv', index=False)

In [4]:
df_pokemon

     id_treinador_batalha  fk_treinador_id  fk_batalha_id
0                       1              113            225
1                       2               26            126
2                       3              165             79
3                       4               10            171
4                       5              218            205
..                    ...              ...            ...
248                   249               34            141
249                   250              159             53
250                   251              247             49
251                   252               74             94
252                   253               93            110

[253 rows x 3 columns]

In [5]:
linhas = []

for i in range(1, 169):
    id = random.randint(1, 2)
    id_2 = random.randint(1, 2)

    if id == 1:
        escudo_1_uso = True
    else:
        escudo_1_uso = False

    if id_2 == 1:
        escudo_2_uso = True
    else:
        escudo_2_uso = False

    dano_causado_pokemon_1 = random.randint(1, 100)
    dano_causado_pokemon_2 = random.randint(1, 100)

    habilidade_pokemon_1 = random.randint(1, 600)
    habilidade_pokemon_2 = random.randint(1, 600)

    fk_round_id = random.randint(1, 169)

    linhas.append([i, escudo_1_uso, escudo_2_uso, dano_causado_pokemon_1, dano_causado_pokemon_2, habilidade_pokemon_1, habilidade_pokemon_2, fk_round_id])

df = pd.DataFrame(linhas, columns=['id_turno', 'escudo_1_uso', 'escudo_2_uso', 'dano_causado_pokemon_1', 'dano_causado_pokemon_2', 'habilidade_pokemon_1', 'habilidade_pokemon_2', 'fk_round_id'])
df.to_csv('../output_data/popular_turno.csv', index=False)